### ISSUE TITLE
Team chat

### ISSUE THREAD

**Issue by Anthony-De** [PvP-Club/server#16]
Chat for each team.

**Comment by Anthony-De** [comment]
There would be a command to enable/disable team chat.

**Comment by BrownHedgehog78** [comment]
Would be better if you write a command like: /tc <message>

**Comment by Anthony-De** [comment]
This issue was added via:
https://github.com/PvP-Club/server/commit/cfa6f7fe1fbe65a57be4624d41449167d7b7ca87
