### ISSUE TITLE
Add pistols

### ISSUE THREAD

**Issue by Anthony-De** [PvP-Club/server#18]
Add a guns mod

**Comment by BrownHedgehog78** [comment]
Only pistol.

**Comment by Anthony-De** [comment]
A gun mod can be found here.
https://content.minetest.net/packages/davidthecreator/rangedweapons/
This is its dependency:
https://content.minetest.net/packages/Calinou/moreores/

**Comment by BrownHedgehog78** [comment]
Will be added.

**Comment by moreavy** [comment]
Wait, If we add pistols, that will create bugs according to the code.

**Comment by Anthony-De** [comment]
@moreavy 
What do you mean?

**Comment by moreavy** [comment]
> @moreavy
> What do you mean?

Pistols don't work in the game according to our code. Whenever a player will die, the kills/deaths won't be counted because pistol dying reason isn't punch.

**Comment by Anthony-De** [comment]
I was considering adding a pistol from the Ranged Weapons mods by davidthecreator. 
From what I saw in the code it deals damage by "punching" the entities. So, the code we are currently using should work.

**Comment by BrownHedgehog78** [comment]
Does the pistol break something?

**Comment by Anthony-De** [comment]
@DiamondPlane It doesn't break anything, it just might fail to work with the current setup on the server.

**Comment by moreavy** [comment]
> I was considering adding a pistol from the Ranged Weapons mods by davidthecreator.
> From what I saw in the code it deals damage by "punching" the entities. So, the code we are currently using should work.

The reason isn't punch. I tested.

**Comment by BrownHedgehog78** [comment]
> it just might fail to work with the current setup on the server.

What do you mean? @Anthony-De

**Comment by Anthony-De** [comment]
@DiamondPlane For one thing, it would fail to recognize the cause of death as being from another player. It would need some work.

**Comment by moreavy** [comment]
I think I can fix that!

**Comment by BrownHedgehog78** [comment]
> @DiamondPlane For one thing, it would fail to recognize the cause of death as being from another player. It would need some work.

I know that it crashes when you kill.
