### ISSUE TITLE
Add the Vehicle Mash mod

### ISSUE THREAD

**Issue by Panquesito7** [PvP-Club/server#58]
Please consider adding the [**Vehicle Mash**](https://github.com/minetest-mods/vehicle_mash). IMO, it'd be great. 🙂

**Comment by RyanZem** [comment]
> Please consider adding the [**Vehicle Mash**](https://github.com/minetest-mods/vehicle_mash). IMO, it'd be great.

Hi Panquesito7, there is the mod in the server that was added some months ago.
